main : tr.c
	gcc -c run.c -o ../obj/run.o
	gcc -c tr.c -o ../obj/main.o 
	gcc -c p1.c -o ../obj/p1.o 
	gcc -c p2.c -o ../obj/p2.o 
	gcc -c p3.c -o ../obj/p3.o 
	gcc -c p4.c -o ../obj/p4.o 
	gcc -c p5.c -o ../obj/p5.o 
	gcc -c p6.c -o ../obj/p6.o 